import { swiperFuncBenefits } from "./modules/sliderBenefits";
import { sliderServices } from "./modules/sliderServices";
import servicesModal from "./modules/servicesModal";
import callbackModal from "./modules/callbackModal";
import scroll from "./modules/scroll";
import modalImg from "./modules/modalImg";
import timer from "./modules/timer";
import calc from "./modules/calc";
swiperFuncBenefits();
sliderServices();
servicesModal();
callbackModal();
scroll();
modalImg();
timer("21 marth 2023");
calc();
